// export const BASE_URL = "https://freelance-api.deelance.com";
export const BASE_URL = "http://localhost:4000";

export const getUserProfilePhoto = (userid: number | string) => {
  return `${BASE_URL}/uploads/${userid}.jpg`;
};

export const FREELANCER = "freelancer";
export const JOB = "job";

const CERTIFICATE_KEY = "certificates";
const EXPERIENCE_KEY = "experience";

export const localStorageKeys = {
  CERTIFICATE_KEY,
  EXPERIENCE_KEY,
};

export const orderStatusLabels = {
  "awaiting-freelancer-approval": "Pending Approval",
  active: "In Progress",
  revision: "Revision",
  completed: "Completed",
  delivered: "Delivered",
  disputed: "Disputed",
  "freelancer-declined": "Declined",
  "client-withdrawn": "Withdrawn",
};

export const countries = [
  { label: "Afghanistan", value: "AF" },
  { label: "Åland Islands", value: "AX" },
  { label: "Albania", value: "AL" },
  { label: "Algeria", value: "DZ" },
  { label: "American Samoa", value: "AS" },
  { label: "AndorrA", value: "AD" },
  { label: "Angola", value: "AO" },
  { label: "Anguilla", value: "AI" },
  { label: "Antarctica", value: "AQ" },
  { label: "Antigua and Barbuda", value: "AG" },
  { label: "Argentina", value: "AR" },
  { label: "Armenia", value: "AM" },
  { label: "Aruba", value: "AW" },
  { label: "Australia", value: "AU" },
  { label: "Austria", value: "AT" },
  { label: "Azerbaijan", value: "AZ" },
  { label: "Bahamas", value: "BS" },
  { label: "Bahrain", value: "BH" },
  { label: "Bangladesh", value: "BD" },
  { label: "Barbados", value: "BB" },
  { label: "Belarus", value: "BY" },
  { label: "Belgium", value: "BE" },
  { label: "Belize", value: "BZ" },
  { label: "Benin", value: "BJ" },
  { label: "Bermuda", value: "BM" },
  { label: "Bhutan", value: "BT" },
  { label: "Bolivia", value: "BO" },
  { label: "Bosnia and Herzegovina", value: "BA" },
  { label: "Botswana", value: "BW" },
  { label: "Bouvet Island", value: "BV" },
  { label: "Brazil", value: "BR" },
  { label: "British Indian Ocean Territory", value: "IO" },
  { label: "Brunei Darussalam", value: "BN" },
  { label: "Bulgaria", value: "BG" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cambodia", value: "KH" },
  { label: "Cameroon", value: "CM" },
  { label: "Canada", value: "CA" },
  { label: "Cape Verde", value: "CV" },
  { label: "Cayman Islands", value: "KY" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Chile", value: "CL" },
  { label: "China", value: "CN" },
  { label: "Christmas Island", value: "CX" },
  { label: "Cocos (Keeling) Islands", value: "CC" },
  { label: "Colombia", value: "CO" },
  { label: "Comoros", value: "KM" },
  { label: "Congo", value: "CG" },
  { label: "Congo, The Democratic Republic of the", value: "CD" },
  { label: "Cook Islands", value: "CK" },
  { label: "Costa Rica", value: "CR" },
  { label: "Cote D'Ivoire", value: "CI" },
  { label: "Croatia", value: "HR" },
  { label: "Cuba", value: "CU" },
  { label: "Cyprus", value: "CY" },
  { label: "Czech Republic", value: "CZ" },
  { label: "Denmark", value: "DK" },
  { label: "Djibouti", value: "DJ" },
  { label: "Dominica", value: "DM" },
  { label: "Dominican Republic", value: "DO" },
  { label: "Ecuador", value: "EC" },
  { label: "Egypt", value: "EG" },
  { label: "El Salvador", value: "SV" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Estonia", value: "EE" },
  { label: "Ethiopia", value: "ET" },
  { label: "Falkland Islands (Malvinas)", value: "FK" },
  { label: "Faroe Islands", value: "FO" },
  { label: "Fiji", value: "FJ" },
  { label: "Finland", value: "FI" },
  { label: "France", value: "FR" },
  { label: "French Guiana", value: "GF" },
  { label: "French Polynesia", value: "PF" },
  { label: "French Southern Territories", value: "TF" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Georgia", value: "GE" },
  { label: "Germany", value: "DE" },
  { label: "Ghana", value: "GH" },
  { label: "Gibraltar", value: "GI" },
  { label: "Greece", value: "GR" },
  { label: "Greenland", value: "GL" },
  { label: "Grenada", value: "GD" },
  { label: "Guadeloupe", value: "GP" },
  { label: "Guam", value: "GU" },
  { label: "Guatemala", value: "GT" },
  { label: "Guernsey", value: "GG" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Guyana", value: "GY" },
  { label: "Haiti", value: "HT" },
  { label: "Heard Island and Mcdonald Islands", value: "HM" },
  { label: "Holy See (Vatican City State)", value: "VA" },
  { label: "Honduras", value: "HN" },
  { label: "Hong Kong", value: "HK" },
  { label: "Hungary", value: "HU" },
  { label: "Iceland", value: "IS" },
  { label: "India", value: "IN" },
  { label: "Indonesia", value: "ID" },
  { label: "Iran, Islamic Republic Of", value: "IR" },
  { label: "Iraq", value: "IQ" },
  { label: "Ireland", value: "IE" },
  { label: "Isle of Man", value: "IM" },
  { label: "Israel", value: "IL" },
  { label: "Italy", value: "IT" },
  { label: "Jamaica", value: "JM" },
  { label: "Japan", value: "JP" },
  { label: "Jersey", value: "JE" },
  { label: "Jordan", value: "JO" },
  { label: "Kazakhstan", value: "KZ" },
  { label: "Kenya", value: "KE" },
  { label: "Kiribati", value: "KI" },
  { label: "Korea, Democratic People'S Republic of", value: "KP" },
  { label: "Korea, Republic of", value: "KR" },
  { label: "Kuwait", value: "KW" },
  { label: "Kyrgyzstan", value: "KG" },
  { label: "Lao People'S Democratic Republic", value: "LA" },
  { label: "Latvia", value: "LV" },
  { label: "Lebanon", value: "LB" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libyan Arab Jamahiriya", value: "LY" },
  { label: "Liechtenstein", value: "LI" },
  { label: "Lithuania", value: "LT" },
  { label: "Luxembourg", value: "LU" },
  { label: "Macao", value: "MO" },
  { label: "Macedonia, The Former Yugoslav Republic of", value: "MK" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Malaysia", value: "MY" },
  { label: "Maldives", value: "MV" },
  { label: "Mali", value: "ML" },
  { label: "Malta", value: "MT" },
  { label: "Marshall Islands", value: "MH" },
  { label: "Martinique", value: "MQ" },
  { label: "Mauritania", value: "MR" },
  { label: "Mauritius", value: "MU" },
  { label: "Mayotte", value: "YT" },
  { label: "Mexico", value: "MX" },
  { label: "Micronesia, Federated States of", value: "FM" },
  { label: "Moldova, Republic of", value: "MD" },
  { label: "Monaco", value: "MC" },
  { label: "Mongolia", value: "MN" },
  { label: "Montserrat", value: "MS" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Myanmar", value: "MM" },
  { label: "Namibia", value: "NA" },
  { label: "Nauru", value: "NR" },
  { label: "Nepal", value: "NP" },
  { label: "Netherlands", value: "NL" },
  { label: "Netherlands Antilles", value: "AN" },
  { label: "New Caledonia", value: "NC" },
  { label: "New Zealand", value: "NZ" },
  { label: "Nicaragua", value: "NI" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "Niue", value: "NU" },
  { label: "Norfolk Island", value: "NF" },
  { label: "Northern Mariana Islands", value: "MP" },
  { label: "Norway", value: "NO" },
  { label: "Oman", value: "OM" },
  { label: "Pakistan", value: "PK" },
  { label: "Palau", value: "PW" },
  { label: "Palestinian Territory, Occupied", value: "PS" },
  { label: "Panama", value: "PA" },
  { label: "Papua New Guinea", value: "PG" },
  { label: "Paraguay", value: "PY" },
  { label: "Peru", value: "PE" },
  { label: "Philippines", value: "PH" },
  { label: "Pitcairn", value: "PN" },
  { label: "Poland", value: "PL" },
  { label: "Portugal", value: "PT" },
  { label: "Puerto Rico", value: "PR" },
  { label: "Qatar", value: "QA" },
  { label: "Reunion", value: "RE" },
  { label: "Romania", value: "RO" },
  { label: "Russian Federation", value: "RU" },
  { label: "RWANDA", value: "RW" },
  { label: "Saint Helena", value: "SH" },
  { label: "Saint Kitts and Nevis", value: "KN" },
  { label: "Saint Lucia", value: "LC" },
  { label: "Saint Pierre and Miquelon", value: "PM" },
  { label: "Saint Vincent and the Grenadines", value: "VC" },
  { label: "Samoa", value: "WS" },
  { label: "San Marino", value: "SM" },
  { label: "Sao Tome and Principe", value: "ST" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Senegal", value: "SN" },
  { label: "Serbia and Montenegro", value: "CS" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Singapore", value: "SG" },
  { label: "Slovakia", value: "SK" },
  { label: "Slovenia", value: "SI" },
  { label: "Solomon Islands", value: "SB" },
  { label: "Somalia", value: "SO" },
  { label: "South Africa", value: "ZA" },
  { label: "South Georgia and the South Sandwich Islands", value: "GS" },
  { label: "Spain", value: "ES" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Sudan", value: "SD" },
  { label: "Surilabel", value: "SR" },
  { label: "Svalbard and Jan Mayen", value: "SJ" },
  { label: "Swaziland", value: "SZ" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Syrian Arab Republic", value: "SY" },
  { label: "Taiwan, Province of China", value: "TW" },
  { label: "Tajikistan", value: "TJ" },
  { label: "Tanzania, United Republic of", value: "TZ" },
  { label: "Thailand", value: "TH" },
  { label: "Timor-Leste", value: "TL" },
  { label: "Togo", value: "TG" },
  { label: "Tokelau", value: "TK" },
  { label: "Tonga", value: "TO" },
  { label: "Trinidad and Tobago", value: "TT" },
  { label: "Tunisia", value: "TN" },
  { label: "Turkey", value: "TR" },
  { label: "Turkmenistan", value: "TM" },
  { label: "Turks and Caicos Islands", value: "TC" },
  { label: "Tuvalu", value: "TV" },
  { label: "Uganda", value: "UG" },
  { label: "Ukraine", value: "UA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "United Kingdom", value: "GB" },
  { label: "United States", value: "US" },
  { label: "United States Minor Outlying Islands", value: "UM" },
  { label: "Uruguay", value: "UY" },
  { label: "Uzbekistan", value: "UZ" },
  { label: "Vanuatu", value: "VU" },
  { label: "Venezuela", value: "VE" },
  { label: "Viet Nam", value: "VN" },
  { label: "Virgin Islands, British", value: "VG" },
  { label: "Virgin Islands, U.S.", value: "VI" },
  { label: "Wallis and Futuna", value: "WF" },
  { label: "Western Sahara", value: "EH" },
  { label: "Yemen", value: "YE" },
  { label: "Zambia", value: "ZM" },
  { label: "Zimbabwe", value: "ZW" },
];

export const languages = [
  { label: "Afrikaans", code: "af" },
  { label: "Albanian", code: "sq" },
  { label: "Arabic (Algeria)", code: "ar-dz" },
  { label: "Arabic (Bahrain)", code: "ar-bh" },
  { label: "Arabic (Egypt)", code: "ar-eg" },
  { label: "Arabic (Iraq)", code: "ar-iq" },
  { label: "Arabic (Jordan)", code: "ar-jo" },
  { label: "Arabic (Kuwait)", code: "ar-kw" },
  { label: "Arabic (Lebanon)", code: "ar-lb" },
  { label: "Arabic (Libya)", code: "ar-ly" },
  { label: "Arabic (Morocco)", code: "ar-ma" },
  { label: "Arabic (Oman)", code: "ar-om" },
  { label: "Arabic (Qatar)", code: "ar-qa" },
  { label: "Arabic (Saudi Arabia)", code: "ar-sa" },
  { label: "Arabic (Syria)", code: "ar-sy" },
  { label: "Arabic (Tunisia)", code: "ar-tn" },
  { label: "Arabic (U.A.E.)", code: "ar-ae" },
  { label: "Arabic (Yemen)", code: "ar-ye" },
  { label: "Basque", code: "eu" },
  { label: "Belarusian", code: "be" },
  { label: "Bulgarian", code: "bg" },
  { label: "Catalan", code: "ca" },
  { label: "Chinese (Hong Kong)", code: "zh-hk" },
  { label: "Chinese (PRC)", code: "zh-cn" },
  { label: "Chinese (Singapore)", code: "zh-sg" },
  { label: "Chinese (Taiwan)", code: "zh-tw" },
  { label: "Croatian", code: "hr" },
  { label: "Czech", code: "cs" },
  { label: "Danish", code: "da" },
  { label: "Dutch (Belgium)", code: "nl-be" },
  { label: "Dutch (Standard)", code: "nl" },
  { label: "English", code: "en" },
  { label: "English (Australia)", code: "en-au" },
  { label: "English (Belize)", code: "en-bz" },
  { label: "English (Canada)", code: "en-ca" },
  { label: "English (Ireland)", code: "en-ie" },
  { label: "English (Jamaica)", code: "en-jm" },
  { label: "English (New Zealand)", code: "en-nz" },
  { label: "English (South Africa)", code: "en-za" },
  { label: "English (Trinidad)", code: "en-tt" },
  { label: "English (United Kingdom)", code: "en-gb" },
  { label: "English (United States)", code: "en-us" },
  { label: "Estonian", code: "et" },
  { label: "Faeroese", code: "fo" },
  { label: "Farsi", code: "fa" },
  { label: "Finnish", code: "fi" },
  { label: "French (Belgium)", code: "fr-be" },
  { label: "French (Canada)", code: "fr-ca" },
  { label: "French (Luxembourg)", code: "fr-lu" },
  { label: "French (Standard)", code: "fr" },
  { label: "French (Switzerland)", code: "fr-ch" },
  { label: "Gaelic (Scotland)", code: "gd" },
  { label: "German (Austria)", code: "de-at" },
  { label: "German (Liechtenstein)", code: "de-li" },
  { label: "German (Luxembourg)", code: "de-lu" },
  { label: "German (Standard)", code: "de" },
  { label: "German (Switzerland)", code: "de-ch" },
  { label: "Greek", code: "el" },
  { label: "Hebrew", code: "he" },
  { label: "Hindi", code: "hi" },
  { label: "Hungarian", code: "hu" },
  { label: "Icelandic", code: "is" },
  { label: "Indonesian", code: "id" },
  { label: "Irish", code: "ga" },
  { label: "Italian (Standard)", code: "it" },
  { label: "Italian (Switzerland)", code: "it-ch" },
  { label: "Japanese", code: "ja" },
  { label: "Korean", code: "ko" },
  { label: "Korean (Johab)", code: "ko" },
  { label: "Kurdish", code: "ku" },
  { label: "Latvian", code: "lv" },
  { label: "Lithuanian", code: "lt" },
  { label: "Macedonian (FYROM)", code: "mk" },
  { label: "Malayalam", code: "ml" },
  { label: "Malaysian", code: "ms" },
  { label: "Maltese", code: "mt" },
  { label: "Norwegian", code: "no" },
  { label: "Norwegian (Bokmål)", code: "nb" },
  { label: "Norwegian (Nynorsk)", code: "nn" },
  { label: "Polish", code: "pl" },
  { label: "Portuguese (Brazil)", code: "pt-br" },
  { label: "Portuguese (Portugal)", code: "pt" },
  { label: "Punjabi", code: "pa" },
  { label: "Rhaeto-Romanic", code: "rm" },
  { label: "Romanian", code: "ro" },
  { label: "Romanian (Republic of Moldova)", code: "ro-md" },
  { label: "Russian", code: "ru" },
  { label: "Russian (Republic of Moldova)", code: "ru-md" },
  { label: "Serbian", code: "sr" },
  { label: "Slovak", code: "sk" },
  { label: "Slovenian", code: "sl" },
  { label: "Sorbian", code: "sb" },
  { label: "Spanish (Argentina)", code: "es-ar" },
  { label: "Spanish (Bolivia)", code: "es-bo" },
  { label: "Spanish (Chile)", code: "es-cl" },
  { label: "Spanish (Colombia)", code: "es-co" },
  { label: "Spanish (Costa Rica)", code: "es-cr" },
  { label: "Spanish (Dominican Republic)", code: "es-do" },
  { label: "Spanish (Ecuador)", code: "es-ec" },
  { label: "Spanish (El Salvador)", code: "es-sv" },
  { label: "Spanish (Guatemala)", code: "es-gt" },
  { label: "Spanish (Honduras)", code: "es-hn" },
  { label: "Spanish (Mexico)", code: "es-mx" },
  { label: "Spanish (Nicaragua)", code: "es-ni" },
  { label: "Spanish (Panama)", code: "es-pa" },
  { label: "Spanish (Paraguay)", code: "es-py" },
  { label: "Spanish (Peru)", code: "es-pe" },
  { label: "Spanish (Puerto Rico)", code: "es-pr" },
  { label: "Spanish (Spain)", code: "es" },
  { label: "Spanish (Uruguay)", code: "es-uy" },
  { label: "Spanish (Venezuela)", code: "es-ve" },
  { label: "Swedish", code: "sv" },
  { label: "Swedish (Finland)", code: "sv-fi" },
  { label: "Thai", code: "th" },
  { label: "Tsonga", code: "ts" },
  { label: "Tswana", code: "tn" },
  { label: "Turkish", code: "tr" },
  { label: "Ukrainian", code: "ua" },
  { label: "Urdu", code: "ur" },
  { label: "Venda", code: "ve" },
  { label: "Vietnamese", code: "vi" },
  { label: "Welsh", code: "cy" },
  { label: "Xhosa", code: "xh" },
  { label: "Yiddish", code: "ji" },
  { label: "Zulu", code: "zu" },
];

export const timezones = [
  { country: "Afghanistan", timeZone: "GMT+04:30" },
  { country: "Albania", timeZone: "GMT+01:00" },
  { country: "Algeria", timeZone: "GMT" },
  { country: "American Samoa", timeZone: "GMT-11:00" },
  { country: "Andorra", timeZone: "GMT+01:00" },
  { country: "Angola", timeZone: "GMT+01:00" },
  { country: "Anguilla", timeZone: "GMT-04:00" },
  { country: "Antarctica", timeZone: "GMT+12:00" },
  { country: "Antigua and Barbuda", timeZone: "GMT-04:00" },
  { country: "Argentina", timeZone: "GMT-03:00" },
  { country: "Armenia", timeZone: "GMT+04:00" },
  { country: "Aruba", timeZone: "GMT-04:00" },
  { country: "Australia", timeZone: "GMT+10:00" },
  { country: "Austria", timeZone: "GMT+01:00" },
  { country: "Azerbaijan", timeZone: "GMT+04:00" },
  { country: "Bahamas", timeZone: "GMT-05:00" },
  { country: "Bahrain", timeZone: "GMT+03:00" },
  { country: "Bangladesh", timeZone: "GMT+06:00" },
  { country: "Barbados", timeZone: "GMT-04:00" },
  { country: "Belarus", timeZone: "GMT+03:00" },
  { country: "Belgium", timeZone: "GMT+01:00" },
  { country: "Belize", timeZone: "GMT-06:00" },
  { country: "Benin", timeZone: "GMT+01:00" },
  { country: "Bermuda", timeZone: "GMT-04:00" },
  { country: "Bhutan", timeZone: "GMT+05:30" },
  { country: "Bolivia", timeZone: "GMT-04:00" },
  { country: "Bosnia and Herzegovina", timeZone: "GMT+01:00" },
  { country: "Botswana", timeZone: "GMT+02:00" },
  { country: "Brazil", timeZone: "GMT-03:00" },
  { country: "British Indian Ocean Territory", timeZone: "GMT+06:00" },
  { country: "British Virgin Islands", timeZone: "GMT-04:00" },
  { country: "Brunei", timeZone: "GMT+08:00" },
  { country: "Bulgaria", timeZone: "GMT+02:00" },
  { country: "Burkina Faso", timeZone: "GMT" },
  { country: "Burma (Myanmar)", timeZone: "GMT+06:30" },
  { country: "Burundi", timeZone: "GMT+02:00" },
  { country: "Cabo Verde", timeZone: "GMT-01:00" },
  { country: "Cambodia", timeZone: "GMT+07:00" },
  { country: "Cameroon", timeZone: "GMT+01:00" },
  { country: "Canada", timeZone: "Multiple Time Zones" },
  { country: "Cayman Islands", timeZone: "GMT-05:00" },
  { country: "Central African Republic", timeZone: "GMT+01:00" },
  { country: "Chad", timeZone: "GMT+01:00" },
  { country: "Chile", timeZone: "GMT-03:00" },
  { country: "China", timeZone: "GMT+08:00" },
  { country: "Christmas Island", timeZone: "GMT+07:00" },
  { country: "Cocos (Keeling) Islands", timeZone: "GMT+06:30" },
  { country: "Colombia", timeZone: "GMT-05:00" },
  { country: "Comoros", timeZone: "GMT+03:00" },
  { country: "Cook Islands", timeZone: "GMT-10:00" },
  { country: "Costa Rica", timeZone: "GMT-06:00" },
  { country: "Côte d'Ivoire", timeZone: "GMT" },
  { country: "Croatia", timeZone: "GMT+01:00" },
  { country: "Cuba", timeZone: "GMT-05:00" },
  { country: "Curaçao", timeZone: "GMT-04:00" },
  { country: "Cyprus", timeZone: "GMT+02:00" },
  { country: "Czechia", timeZone: "GMT+01:00" },
  { country: "Denmark", timeZone: "GMT+01:00" },
  { country: "Djibouti", timeZone: "GMT+03:00" },
  { country: "Dominica", timeZone: "GMT-04:00" },
  { country: "Dominican Republic", timeZone: "GMT-04:00" },
  { country: "Ecuador", timeZone: "GMT-05:00" },
  { country: "Egypt", timeZone: "GMT+02:00" },
  { country: "El Salvador", timeZone: "GMT-06:00" },
  { country: "Equatorial Guinea", timeZone: "GMT+01:00" },
  { country: "Eritrea", timeZone: "GMT+03:00" },
  { country: "Estonia", timeZone: "GMT+02:00" },
  { country: "Eswatini", timeZone: "GMT+02:00" },
  { country: "Ethiopia", timeZone: "GMT+03:00" },
  { country: "Falkland Islands", timeZone: "GMT-03:00" },
  { country: "Faroe Islands", timeZone: "GMT" },
  { country: "Fiji", timeZone: "GMT+12:00" },
  { country: "Finland", timeZone: "GMT+02:00" },
  { country: "France", timeZone: "GMT+01:00" },
  { country: "French Guiana", timeZone: "GMT-03:00" },
  { country: "French Polynesia", timeZone: "GMT-10:00" },
  { country: "Gabon", timeZone: "GMT+01:00" },
  { country: "Gambia", timeZone: "GMT" },
  { country: "Georgia", timeZone: "GMT+04:00" },
  { country: "Germany", timeZone: "GMT+01:00" },
  { country: "Ghana", timeZone: "GMT" },
  { country: "Gibraltar", timeZone: "GMT+01:00" },
  { country: "Greece", timeZone: "GMT+02:00" },
  { country: "Greenland", timeZone: "Multiple Time Zones" },
  { country: "Grenada", timeZone: "GMT-04:00" },
  { country: "Guadeloupe", timeZone: "GMT-04:00" },
  { country: "Guam", timeZone: "GMT+10:00" },
  { country: "Guatemala", timeZone: "GMT-06:00" },
  { country: "Guernsey", timeZone: "GMT" },
  { country: "Guinea", timeZone: "GMT" },
  { country: "Guinea-Bissau", timeZone: "GMT" },
  { country: "Guyana", timeZone: "GMT-04:00" },
  { country: "Haiti", timeZone: "GMT-05:00" },
  { country: "Honduras", timeZone: "GMT-06:00" },
  { country: "Hong Kong", timeZone: "GMT+08:00" },
  { country: "Hungary", timeZone: "GMT+01:00" },
  { country: "Iceland", timeZone: "GMT" },
  { country: "India", timeZone: "GMT+05:30" },
  { country: "Indonesia", timeZone: "Multiple Time Zones" },
  { country: "Iran", timeZone: "GMT+03:30" },
  { country: "Iraq", timeZone: "GMT+03:00" },
  { country: "Ireland", timeZone: "GMT" },
  { country: "Isle of Man", timeZone: "GMT" },
  { country: "Israel", timeZone: "GMT+02:00" },
  { country: "Italy", timeZone: "GMT+01:00" },
  { country: "Jamaica", timeZone: "GMT-05:00" },
  { country: "Japan", timeZone: "GMT+09:00" },
  { country: "Jersey", timeZone: "GMT" },
  { country: "Jordan", timeZone: "GMT+03:00" },
  { country: "Kazakhstan", timeZone: "GMT+06:00" },
  { country: "Kenya", timeZone: "GMT+03:00" },
  { country: "Kiribati", timeZone: "Multiple Time Zones" },
  { country: "Kuwait", timeZone: "GMT+03:00" },
  { country: "Kyrgyzstan", timeZone: "GMT+06:00" },
  { country: "Laos", timeZone: "GMT+07:00" },
  { country: "Latvia", timeZone: "GMT+02:00" },
  { country: "Lebanon", timeZone: "GMT+02:00" },
  { country: "Lesotho", timeZone: "GMT+02:00" },
  { country: "Liberia", timeZone: "GMT" },
  { country: "Libya", timeZone: "GMT+02:00" },
  { country: "Liechtenstein", timeZone: "GMT+01:00" },
  { country: "Lithuania", timeZone: "GMT+02:00" },
  { country: "Luxembourg", timeZone: "GMT+01:00" },
  { country: "Macau", timeZone: "GMT+08:00" },
  { country: "North Macedonia", timeZone: "GMT+01:00" },
  { country: "Madagascar", timeZone: "GMT+03:00" },
  { country: "Malawi", timeZone: "GMT+02:00" },
  { country: "Malaysia", timeZone: "GMT+08:00" },
  { country: "Maldives", timeZone: "GMT+05:00" },
  { country: "Mali", timeZone: "GMT" },
  { country: "Malta", timeZone: "GMT+01:00" },
  { country: "Marshall Islands", timeZone: "GMT+12:00" },
  { country: "Martinique", timeZone: "GMT-04:00" },
  { country: "Mauritania", timeZone: "GMT" },
  { country: "Mauritius", timeZone: "GMT+04:00" },
  { country: "Mayotte", timeZone: "GMT+03:00" },
  { country: "Mexico", timeZone: "Multiple Time Zones" },
  { country: "Micronesia", timeZone: "GMT+10:00" },
  { country: "Moldova", timeZone: "GMT+02:00" },
  { country: "Monaco", timeZone: "GMT+01:00" },
  { country: "Mongolia", timeZone: "GMT+08:00" },
  { country: "Montenegro", timeZone: "GMT+01:00" },
  { country: "Montserrat", timeZone: "GMT-04:00" },
  { country: "Morocco", timeZone: "GMT" },
  { country: "Mozambique", timeZone: "GMT+02:00" },
  { country: "Namibia", timeZone: "GMT+02:00" },
  { country: "Nauru", timeZone: "GMT+12:00" },
  { country: "Nepal", timeZone: "GMT+05:45" },
  { country: "Netherlands", timeZone: "GMT+01:00" },
  { country: "New Caledonia", timeZone: "GMT+11:00" },
  { country: "New Zealand", timeZone: "Multiple Time Zones" },
  { country: "Nicaragua", timeZone: "GMT-06:00" },
  { country: "Niger", timeZone: "GMT+01:00" },
  { country: "Nigeria", timeZone: "GMT+01:00" },
  { country: "Niue", timeZone: "GMT-11:00" },
  { country: "Norfolk Island", timeZone: "GMT+11:00" },
  { country: "North Korea", timeZone: "GMT+09:00" },
  { country: "Northern Mariana Islands", timeZone: "GMT+10:00" },
  { country: "Norway", timeZone: "GMT+01:00" },
  { country: "Oman", timeZone: "GMT+04:00" },
  { country: "Pakistan", timeZone: "GMT+05:00" },
  { country: "Palau", timeZone: "GMT+09:00" },
  { country: "Panama", timeZone: "GMT-05:00" },
  { country: "Papua New Guinea", timeZone: "GMT+10:00" },
  { country: "Paraguay", timeZone: "GMT-04:00" },
  { country: "Peru", timeZone: "GMT-05:00" },
  { country: "Philippines", timeZone: "GMT+08:00" },
  { country: "Pitcairn Islands", timeZone: "GMT-08:00" },
  { country: "Poland", timeZone: "GMT+01:00" },
  { country: "Portugal", timeZone: "GMT" },
  { country: "Puerto Rico", timeZone: "GMT-04:00" },
  { country: "Qatar", timeZone: "GMT+03:00" },
  { country: "Réunion", timeZone: "GMT+04:00" },
  { country: "Romania", timeZone: "GMT+02:00" },
  { country: "Russia", timeZone: "Multiple Time Zones" },
  { country: "Rwanda", timeZone: "GMT+02:00" },
  { country: "Saint Barthélemy", timeZone: "GMT-04:00" },
  { country: "Saint Helena", timeZone: "GMT" },
  { country: "Saint Kitts and Nevis", timeZone: "GMT-04:00" },
  { country: "Saint Lucia", timeZone: "GMT-04:00" },
  { country: "Saint Martin", timeZone: "GMT-04:00" },
  { country: "Saint Pierre and Miquelon", timeZone: "GMT-03:00" },
  { country: "Saint Vincent and the Grenadines", timeZone: "GMT-04:00" },
  { country: "Samoa", timeZone: "GMT+13:00" },
  { country: "San Marino", timeZone: "GMT+01:00" },
  { country: "São Tomé and Príncipe", timeZone: "GMT" },
  { country: "Saudi Arabia", timeZone: "GMT+03:00" },
  { country: "Senegal", timeZone: "GMT" },
  { country: "Serbia", timeZone: "GMT+01:00" },
  { country: "Seychelles", timeZone: "GMT+04:00" },
  { country: "Sierra Leone", timeZone: "GMT" },
  { country: "Singapore", timeZone: "GMT+08:00" },
  { country: "Sint Maarten", timeZone: "GMT-04:00" },
  { country: "Slovakia", timeZone: "GMT+01:00" },
  { country: "Slovenia", timeZone: "GMT+01:00" },
  { country: "Solomon Islands", timeZone: "GMT+11:00" },
  { country: "Somalia", timeZone: "GMT+03:00" },
  { country: "South Africa", timeZone: "Multiple Time Zones" },
  {
    country: "South Georgia and South Sandwich Islands",
    timeZone: "GMT-02:00",
  },
  { country: "South Korea", timeZone: "GMT+09:00" },
  { country: "South Sudan", timeZone: "GMT+03:00" },
  { country: "Spain", timeZone: "GMT+01:00" },
  { country: "Sri Lanka", timeZone: "GMT+05:30" },
  { country: "Sudan", timeZone: "GMT+02:00" },
  { country: "Suriname", timeZone: "GMT-03:00" },
  { country: "Svalbard and Jan Mayen", timeZone: "GMT+01:00" },
  { country: "Sweden", timeZone: "GMT+01:00" },
  { country: "Switzerland", timeZone: "GMT+01:00" },
  { country: "Syria", timeZone: "GMT+02:00" },
  { country: "Taiwan", timeZone: "GMT+08:00" },
  { country: "Tajikistan", timeZone: "GMT+05:00" },
  { country: "Tanzania", timeZone: "GMT+03:00" },
  { country: "Thailand", timeZone: "GMT+07:00" },
  { country: "Timor-Leste", timeZone: "GMT+09:00" },
  { country: "Togo", timeZone: "GMT" },
  { country: "Tokelau", timeZone: "GMT+13:00" },
  { country: "Tonga", timeZone: "GMT+13:00" },
  { country: "Trinidad and Tobago", timeZone: "GMT-04:00" },
  { country: "Tunisia", timeZone: "GMT+01:00" },
  { country: "Turkey", timeZone: "GMT+03:00" },
  { country: "Turkmenistan", timeZone: "GMT+05:00" },
  { country: "Turks and Caicos Islands", timeZone: "GMT-05:00" },
  { country: "Tuvalu", timeZone: "GMT+12:00" },
  { country: "Uganda", timeZone: "GMT+03:00" },
  { country: "Ukraine", timeZone: "GMT+02:00" },
  { country: "United Arab Emirates", timeZone: "GMT+04:00" },
  { country: "United Kingdom", timeZone: "GMT" },
  { country: "United States", timeZone: "Multiple Time Zones" },
  { country: "Uruguay", timeZone: "GMT-03:00" },
  { country: "Uzbekistan", timeZone: "GMT+05:00" },
  { country: "Vanuatu", timeZone: "GMT+11:00" },
  { country: "Vatican City", timeZone: "GMT+01:00" },
  { country: "Venezuela", timeZone: "GMT-04:00" },
  { country: "Vietnam", timeZone: "GMT+07:00" },
  { country: "Wallis and Futuna", timeZone: "GMT+12:00" },
  { country: "Western Sahara", timeZone: "GMT+01:00" },
  { country: "Yemen", timeZone: "GMT+03:00" },
  { country: "Zambia", timeZone: "GMT+02:00" },
  { country: "Zimbabwe", timeZone: "GMT+02:00" },
];

export const years = [
  { value: "2023", text: "2023" },
  { value: "2022", text: "2022" },
  { value: "2021", text: "2021" },
  { value: "2020", text: "2020" },
  { value: "2019", text: "2019" },
  { value: "2018", text: "2018" },
  { value: "2017", text: "2017" },
  { value: "2016", text: "2016" },
  { value: "2015", text: "2015" },
  { value: "2014", text: "2014" },
  { value: "2013", text: "2013" },
  { value: "2012", text: "2012" },
  { value: "2011", text: "2011" },
  { value: "2010", text: "2010" },
  { value: "2009", text: "2009" },
  { value: "2008", text: "2008" },
  { value: "2007", text: "2007" },
  { value: "2006", text: "2006" },
  { value: "2005", text: "2005" },
  { value: "2004", text: "2004" },
  { value: "2003", text: "2003" },
  { value: "2002", text: "2002" },
  { value: "2001", text: "2001" },
  { value: "2000", text: "2000" },
  { value: "1999", text: "1999" },
  { value: "1998", text: "1998" },
  { value: "1997", text: "1997" },
  { value: "1996", text: "1996" },
  { value: "1995", text: "1995" },
  { value: "1994", text: "1994" },
  { value: "1993", text: "1993" },
  { value: "1992", text: "1992" },
  { value: "1991", text: "1991" },
  { value: "1990", text: "1990" },
  { value: "1989", text: "1989" },
  { value: "1988", text: "1988" },
  { value: "1987", text: "1987" },
  { value: "1986", text: "1986" },
  { value: "1985", text: "1985" },
  { value: "1984", text: "1984" },
  { value: "1983", text: "1983" },
  { value: "1982", text: "1982" },
  { value: "1981", text: "1981" },
  { value: "1980", text: "1980" },
  { value: "1979", text: "1979" },
  { value: "1978", text: "1978" },
  { value: "1977", text: "1977" },
  { value: "1976", text: "1976" },
  { value: "1975", text: "1975" },
  { value: "1974", text: "1974" },
  { value: "1973", text: "1973" },
  { value: "1972", text: "1972" },
  { value: "1971", text: "1971" },
  { value: "1970", text: "1970" },
  { value: "1969", text: "1969" },
  { value: "1968", text: "1968" },
  { value: "1967", text: "1967" },
  { value: "1966", text: "1966" },
  { value: "1965", text: "1965" },
  { value: "1964", text: "1964" },
  { value: "1963", text: "1963" },
  { value: "1962", text: "1962" },
  { value: "1961", text: "1961" },
  { value: "1960", text: "1960" },
  { value: "1959", text: "1959" },
  { value: "1958", text: "1958" },
  { value: "1957", text: "1957" },
  { value: "1956", text: "1956" },
  { value: "1955", text: "1955" },
  { value: "1954", text: "1954" },
  { value: "1953", text: "1953" },
  { value: "1952", text: "1952" },
  { value: "1951", text: "1951" },
  { value: "1950", text: "1950" },
  { value: "1949", text: "1949" },
  { value: "1948", text: "1948" },
  { value: "1947", text: "1947" },
  { value: "1946", text: "1946" },
  { value: "1945", text: "1945" },
  { value: "1944", text: "1944" },
  { value: "1943", text: "1943" },
  { value: "1942", text: "1942" },
  { value: "1941", text: "1941" },
  { value: "1940", text: "1940" },
  { value: "1939", text: "1939" },
  { value: "1938", text: "1938" },
  { value: "1937", text: "1937" },
  { value: "1936", text: "1936" },
  { value: "1935", text: "1935" },
  { value: "1934", text: "1934" },
  { value: "1933", text: "1933" },
  { value: "1932", text: "1932" },
  { value: "1931", text: "1931" },
  { value: "1930", text: "1930" },
  { value: "1929", text: "1929" },
  { value: "1928", text: "1928" },
  { value: "1927", text: "1927" },
  { value: "1926", text: "1926" },
  { value: "1925", text: "1925" },
  { value: "1924", text: "1924" },
  { value: "1923", text: "1923" },
];

export const months = [
  { value: "1", title: "January", shortTitle: "Jan" },
  { value: "2", title: "February", shortTitle: "Feb" },
  { value: "3", title: "March", shortTitle: "Mar" },
  { value: "4", title: "April", shortTitle: "Apr" },
  { value: "5", title: "May", shortTitle: "May" },
  { value: "6", title: "June", shortTitle: "Jun" },
  { value: "7", title: "July", shortTitle: "Jul" },
  { value: "8", title: "August", shortTitle: "Aug" },
  { value: "9", title: "September", shortTitle: "Sep" },
  { value: "10", title: "October", shortTitle: "Oct" },
  { value: "11", title: "November", shortTitle: "Nov" },
  { value: "12", title: "December", shortTitle: "Dec" },
];

export const skills = [
  { value: "javascript", label: "Javascript" },
  { value: "html", label: "Html" },
  { value: "css", label: "CSS" },
  { value: "typescript", label: "Typescript" },
  { value: "wordpress", label: "Wordpress" },
  { value: "styled-components", label: "Styled Components" },
  { value: "tailwindcss", label: "Tailwindcss" },
  { value: "reactjs", label: "Reactjs" },
  { value: "nextjs", label: "Nextjs" },
  { value: "material-ui", label: "Material UI" },
];

export const categories = [
  "Graphics & Design",
  "Digital Marketing",
  "Writing & Translation",
  "Video & Animation",
  "Music & Audio",
  "Programming & Tech",
  "Business",
  "Lifestyle",
  "Data",
  "Health & Wellness",
  "Sales & Marketing",
  "Education & Training",
  "Legal",
  "Crafts & Hobbies",
  "Architecture & Interior Design",
  "Social Media Management",
  "Customer Service",
];

export const subcategories = {
  "Graphics & Design": [
    "Logo Design",
    "Illustration",
    "Flyers & Posters",
    "Brochure Design",
    "Packaging Design",
  ],
  "Digital Marketing": [
    "Social Media Marketing",
    "SEO",
    "Content Marketing",
    "Email Marketing",
    "Influencer Marketing",
  ],
  "Writing & Translation": [
    "Articles & Blog Posts",
    "Creative Writing",
    "Translation",
    "Proofreading & Editing",
    "Resumes & Cover Letters",
  ],
  "Video & Animation": [
    "Whiteboard & Explainer Videos",
    "Video Editing",
    "Animated GIFs",
    "Short Video Ads",
    "Character Animation",
  ],
  "Music & Audio": [
    "Voice Over",
    "Mixing & Mastering",
    "Jingles & Drops",
    "Podcast Editing",
    "Music Composition",
  ],
  "Programming & Tech": [
    "WordPress",
    "Web & Mobile Design",
    "E-commerce Development",
    "Game Development",
    "Database Management",
  ],
  Business: [
    "Virtual Assistant",
    "Market Research",
    "Business Plans",
    "Financial Consulting",
    "Project Management",
  ],
  Lifestyle: [
    "Fitness & Nutrition",
    "Relationship Advice",
    "Greeting Cards & Videos",
    "Travel Planning",
    "Event Planning",
  ],
  Data: [
    "Data Entry",
    "Data Analysis",
    "Data Visualization",
    "Database Administration",
    "Machine Learning",
  ],
  "Health & Wellness": [
    "Nutrition Consulting",
    "Fitness Training",
    "Mental Health Support",
    "Holistic Healing",
    "Medical Writing",
  ],
  "Sales & Marketing": [
    "Sales",
    "Lead Generation",
    "Advertising",
    "Brand Strategy",
    "Market Research",
  ],
  "Education & Training": [
    "Online Tutoring",
    "Course Development",
    "Language Lessons",
    "Career Coaching",
    "E-learning",
  ],
  Legal: [
    "Legal Writing",
    "Contract Law",
    "Intellectual Property Law",
    "Legal Consulting",
    "Paralegal Services",
  ],
  "Crafts & Hobbies": [
    "Handmade Crafts",
    "DIY Projects",
    "Knitting & Crochet",
    "Painting & Drawing",
    "Photography",
  ],
  "Architecture & Interior Design": [
    "Architectural Design",
    "Interior Design",
    "3D Modeling",
    "Landscape Design",
    "Urban Planning",
  ],
  "Social Media Management": [
    "Social Media Strategy",
    "Content Creation",
    "Community Management",
    "Social Media Analytics",
    "Influencer Collaboration",
  ],
  "Customer Service": [
    "Customer Support",
    "Live Chat Support",
    "Email Handling",
    "Call Center Services",
    "Technical Support",
  ],
};

export const keywords = {
  "Graphics & Design": [
    "graphic design",
    "logo creation",
    "illustration services",
    "branding",
    "print design",
    "digital art",
    "poster design",
    "packaging design",
    "creative concepts",
    "visual identity",
  ],

  "Digital Marketing": [
    "digital marketing",
    "online advertising",
    "social media promotion",
    "SEO services",
    "content marketing",
    "email campaigns",
    "influencer marketing",
    "online presence",
    "marketing analytics",
    "brand strategy",
  ],

  "Writing & Translation": [
    "content writing",
    "blog posts",
    "copywriting",
    "translation services",
    "proofreading",
    "editing",
    "resumes",
    "cover letters",
    "creative writing",
    "technical writing",
  ],

  "Video & Animation": [
    "video production",
    "animation services",
    "motion graphics",
    "explainer videos",
    "video editing",
    "animated GIFs",
    "short video ads",
    "character animation",
    "3D animation",
    "storyboarding",
  ],

  "Music & Audio": [
    "audio production",
    "music composition",
    "voiceover services",
    "sound design",
    "podcast editing",
    "jingles",
    "background music",
    "audio mixing",
    "audio editing",
    "music production",
  ],

  "Programming & Tech": [
    "web development",
    "software engineering",
    "mobile app development",
    "WordPress",
    "e-commerce development",
    "game development",
    "UI/UX design",
    "database management",
    "API integration",
    "machine learning",
  ],

  Business: [
    "virtual assistant",
    "business consulting",
    "market research",
    "business plans",
    "financial consulting",
    "project management",
    "data analysis",
    "startup advice",
    "business strategy",
    "productivity improvement",
  ],

  Lifestyle: [
    "lifestyle coaching",
    "fitness training",
    "relationship advice",
    "greeting cards creation",
    "event planning",
    "travel planning",
    "personal styling",
    "wellness programs",
    "nutrition coaching",
    "life coaching",
  ],

  Data: [
    "data entry",
    "data analysis",
    "data visualization",
    "database management",
    "data mining",
    "big data analytics",
    "data reporting",
    "data cleaning",
    "database design",
    "business intelligence",
  ],

  "Health & Wellness": [
    "health coaching",
    "wellness programs",
    "mental health support",
    "nutrition counseling",
    "fitness programs",
    "holistic healing",
    "self-care guidance",
    "mindfulness coaching",
    "stress management",
    "health education",
  ],

  "Sales & Marketing": [
    "sales strategies",
    "marketing campaigns",
    "lead generation",
    "branding",
    "market research",
    "advertising",
    "email marketing",
    "social media management",
    "customer engagement",
    "competitive analysis",
  ],

  "Education & Training": [
    "online tutoring",
    "course development",
    "e-learning programs",
    "language lessons",
    "academic tutoring",
    "career coaching",
    "educational consulting",
    "instructional design",
    "online workshops",
    "teacher training",
  ],

  Legal: [
    "legal writing",
    "contract law",
    "intellectual property services",
    "legal consulting",
    "document review",
    "business law",
    "legal research",
    "family law",
    "employment law",
    "immigration law",
  ],

  "Crafts & Hobbies": [
    "handmade crafts",
    "DIY projects",
    "creative hobbies",
    "knitting & crochet",
    "painting & drawing",
    "photography",
    "scrapbooking",
    "calligraphy",
    "pottery",
    "jewelry making",
  ],

  "Architecture & Interior Design": [
    "architectural design",
    "interior decor",
    "3D modeling",
    "landscape design",
    "urban planning",
    "space planning",
    "home staging",
    "architectural drafting",
    "furniture design",
    "building design",
  ],

  "Social Media Management": [
    "social media strategy",
    "content creation",
    "community management",
    "social media analytics",
    "influencer collaboration",
    "online presence",
    "branding on social media",
    "social media advertising",
    "engagement strategies",
    "content scheduling",
  ],

  "Customer Service": [
    "customer support",
    "live chat services",
    "email handling",
    "call center services",
    "technical support",
    "customer satisfaction",
    "issue resolution",
    "customer feedback",
    "order processing",
    "helpdesk support",
  ],
};
